"""Partner syndication and secure embed module."""

from app.modules.partners.api import embed_router, partners_router
from app.modules.partners.models import (
    Partner,
    PartnerApiCredential,
    PartnerBranding,
    PartnerContentType,
    PartnerCredentialStatus,
    PartnerDomain,
    PartnerDomainStatus,
    PartnerEmbedEvent,
    PartnerEmbedEventType,
    PartnerEntitlement,
    PartnerEntitlementStatus,
    PartnerFinancialAuditAction,
    PartnerFinancialAuditLog,
    PartnerPayout,
    PartnerPayoutAccount,
    PartnerPayoutAccountStatus,
    PartnerPayoutAuditAction,
    PartnerPayoutAuditLog,
    PartnerPayoutProviderType,
    PartnerPayoutReconciliation,
    PartnerPayoutReconciliationOutcome,
    PartnerPayoutStatus,
    PartnerPayoutVerificationStatus,
    PartnerRevenueShareAgreement,
    PartnerSettlementStatement,
    PartnerUsageEventType,
    PartnerUsageMeter,
    PartnerStatus,
    RevenueShareRuleType,
    SettlementStatus,
)
from app.modules.partners.repository import PartnerRepository
from app.modules.partners.service import PartnerSecurityError, PartnerSyndicationService

__all__ = [
    "Partner",
    "PartnerApiCredential",
    "PartnerBranding",
    "PartnerContentType",
    "PartnerCredentialStatus",
    "PartnerDomain",
    "PartnerDomainStatus",
    "PartnerEmbedEvent",
    "PartnerEmbedEventType",
    "PartnerEntitlement",
    "PartnerEntitlementStatus",
    "PartnerFinancialAuditAction",
    "PartnerFinancialAuditLog",
    "PartnerPayout",
    "PartnerPayoutAccount",
    "PartnerPayoutAccountStatus",
    "PartnerPayoutAuditAction",
    "PartnerPayoutAuditLog",
    "PartnerPayoutProviderType",
    "PartnerPayoutReconciliation",
    "PartnerPayoutReconciliationOutcome",
    "PartnerPayoutStatus",
    "PartnerPayoutVerificationStatus",
    "PartnerRepository",
    "PartnerRevenueShareAgreement",
    "PartnerSecurityError",
    "PartnerSettlementStatement",
    "PartnerStatus",
    "PartnerSyndicationService",
    "PartnerUsageEventType",
    "PartnerUsageMeter",
    "RevenueShareRuleType",
    "SettlementStatus",
    "embed_router",
    "partners_router",
]
